# Generated by Django 5.0.6 on 2024-07-30 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_cart_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="last_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=25, max_digits=9),
            preserve_default=False,
        ),
    ]
