# Generated by Django 5.0.6 on 2024-07-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_order_last_updated_order_total_cost_orderitem_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_cost",
            new_name="total_price",
        ),
    ]
